import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

import {
  createInboundRecord,
  createOutboundRecord,
  parseDestinationRecord,
  parseDirectOutboundWrite,
  parseInboundRecord,
  parseInboundWrite,
  parseIsoTimestamp,
  parseOutboundRecord,
  parseTaskWrite,
} from './model.js';
import type { IsoTimestamp } from './model.js';

describe('canonical mailbox model', () => {
  it('is generated byte-for-byte into the runner tree', () => {
    const root = process.cwd();
    const source = fs.readFileSync(path.join(root, 'src/mailbox/model.ts'), 'utf8');
    expect(fs.readFileSync(path.join(root, 'container/agent-runner/src/mailbox/model.generated.ts'), 'utf8')).toBe(
      source,
    );
  });

  it('normalizes a complete inbound write into the strict persisted record', () => {
    const record = createInboundRecord(
      {
        id: 'in-1',
        kind: 'chat',
        timestamp: '2026-01-01T00:00:00.000Z',
        platformId: 'room',
        channelType: 'test',
        threadId: 'thread',
        content: '{"text":"hello"}',
        processAfter: null,
        recurrence: null,
        trigger: true,
        sourceSessionId: 'source-session',
        onWake: false,
      },
      2,
    );
    const timestamp: IsoTimestamp = record.timestamp;

    expect(record).toEqual({
      id: 'in-1',
      sequence: 2,
      kind: 'chat',
      timestamp: '2026-01-01T00:00:00.000Z',
      status: 'pending',
      processAfter: null,
      recurrence: null,
      seriesId: 'in-1',
      tries: 0,
      trigger: true,
      platformId: 'room',
      channelType: 'test',
      threadId: 'thread',
      content: '{"text":"hello"}',
      sourceSessionId: 'source-session',
      onWake: false,
    });
    expect(timestamp).toBe('2026-01-01T00:00:00.000Z');
    expect(parseIsoTimestamp(timestamp)).toBe(timestamp);
    expect(() => parseIsoTimestamp('2026-01-01 00:00:00')).toThrow('invalid ISO-8601 UTC timestamp');
  });

  it('normalizes optional outbound values before persistence', () => {
    expect(
      createOutboundRecord(
        {
          id: 'out-1',
          inReplyTo: undefined,
          deliverAfter: undefined,
          recurrence: undefined,
          kind: 'chat',
          platformId: undefined,
          channelType: undefined,
          threadId: undefined,
          content: '{"text":"hi"}',
        },
        3,
        '2026-01-01T00:00:01.000Z',
      ),
    ).toEqual({
      id: 'out-1',
      sequence: 3,
      inReplyTo: null,
      timestamp: '2026-01-01T00:00:01.000Z',
      deliverAfter: null,
      recurrence: null,
      kind: 'chat',
      platformId: null,
      channelType: null,
      threadId: null,
      content: '{"text":"hi"}',
    });
  });

  it('rejects unknown, missing, and representation-drifted fields', () => {
    const inbound = createInboundRecord(
      {
        id: 'in-1',
        kind: 'chat',
        timestamp: '2026-01-01T00:00:00.000Z',
        platformId: null,
        channelType: null,
        threadId: null,
        content: '{}',
        processAfter: null,
        recurrence: null,
      },
      2,
    );
    expect(() => parseInboundRecord({ ...inbound, extraField: 7 })).toThrow('unknown field extraField');
    expect(() => parseInboundRecord({ ...inbound, trigger: 1 })).toThrow('expected boolean');
    expect(() => parseInboundRecord({ ...inbound, timestamp: '2026-01-01 00:00:00' })).toThrow(
      'expected ISO-8601 UTC timestamp',
    );
    expect(() => parseInboundRecord({ ...inbound, tries: -1 })).toThrow('expected nonnegative integer');
    expect(() => parseInboundRecord({ ...inbound, kind: 'unknown' })).toThrow('unexpected value');
    expect(() => parseInboundRecord({ ...inbound, content: { text: 'nested' } })).toThrow('nested field content');
    const { content: _missing, ...withoutContent } = inbound;
    expect(() => parseInboundRecord(withoutContent)).toThrow('content');

    const outbound = createOutboundRecord({ id: 'out-1', kind: 'chat', content: '{}' }, 3, inbound.timestamp);
    expect(parseOutboundRecord(outbound)).toEqual(outbound);
  });

  it('rejects unknown fields on write DTOs before defaults can hide them', () => {
    expect(() =>
      parseTaskWrite({
        id: 'task-1',
        seriesId: 'task-1',
        processAfter: null,
        recurrence: null,
        content: '{}',
        internal: true,
      }),
    ).toThrow('unknown field internal');
    expect(() =>
      parseDirectOutboundWrite({
        id: 'out-1',
        kind: 'chat',
        platformId: null,
        channelType: null,
        threadId: null,
        content: '{}',
        inReplyTo: 'hidden',
      }),
    ).toThrow('unknown field inReplyTo');
  });

  it('keeps storage representations out of write DTOs', () => {
    expect(() =>
      parseInboundWrite({
        id: 'in-1',
        kind: 'chat',
        timestamp: '2026-01-01T00:00:00.000Z',
        platformId: null,
        channelType: null,
        threadId: null,
        content: '{}',
        processAfter: null,
        recurrence: null,
        trigger: 1,
      }),
    ).toThrow('expected boolean');
  });

  it('enforces each destination variant at its parser boundary', () => {
    expect(
      parseDestinationRecord({
        name: 'room',
        displayName: null,
        type: 'channel',
        channelType: 'test',
        platformId: 'room-1',
        agentGroupId: null,
      }),
    ).toMatchObject({ type: 'channel', channelType: 'test', platformId: 'room-1', agentGroupId: null });
    expect(
      parseDestinationRecord({
        name: 'peer',
        displayName: 'Peer Agent',
        type: 'agent',
        channelType: null,
        platformId: null,
        agentGroupId: 'agent-1',
      }),
    ).toMatchObject({ type: 'agent', channelType: null, platformId: null, agentGroupId: 'agent-1' });

    expect(() =>
      parseDestinationRecord({
        name: 'broken-channel',
        displayName: null,
        type: 'channel',
        channelType: null,
        platformId: 'room-1',
        agentGroupId: 'agent-1',
      }),
    ).toThrow('channel routing fields');
    expect(() =>
      parseDestinationRecord({
        name: 'broken-agent',
        displayName: null,
        type: 'agent',
        channelType: 'test',
        platformId: null,
        agentGroupId: null,
      }),
    ).toThrow('agent routing fields');
  });
});
